
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: ms-customer
        uri: lb://ms-customer
        predicates:
          - Path=/api/ms-customer/**
        filters: StripPrefix=2

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka